# https://blog.taoluyuan.com/posts/github-workflows/
name: deploy
on:
  push:
  workflow_dispatch:
jobs:
  # 构建静态HTML代码并推送到GithubPages
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        run: |
          echo github.event: ${{ github.event }}
          echo github.event_path: ${{ github.event_path }}
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.workspace: ${{ github.workspace }}
          echo github.workflow: ${{ github.workflow }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # 同时检出子模块
          submodules: true
          # 完整地检出所有历史记录
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          # hugo extend version
          extended: true

       # https://github.com/Fastbyte01/KeepIt/issues/73#issuecomment-1685037103
       # 这里是为了修复KeepIt主题的bug.
      - name: Fix KeepIt home_post.html Bug
        run: |
          mv themes_bugfix/KeepIt/home_post.html themes/KeepIt/layouts/partials/
          mv themes_bugfix/KeepIt/home_profile.html themes/KeepIt/layouts/partials/

      - name: Build Web
        run: hugo

#      - name: Deploy Web
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          # GitHub Personal Access Tokens 用于访问 GitHub 仓库
#          # 1. 需要到Your Profile/Setting/DevelopSettings/创建Personal access tokens添加repo/*权限
#          # 2. 并在bloggen仓库的 Setting/Secrets，创建名为BLOG_TOKEN的secret,值为token值 中以供 Workflow 使用
#          PERSONAL_TOKEN: ${{ secrets.BLOG_TOKEN }}
#          #  部署到的 GitHub Pages 仓库
#          EXTERNAL_REPOSITORY: wangweihong/wangweihong.github.io
#          PUBLISH_BRANCH: master
#          # hugo 静态html文件目录。（在此例中，Hugo 输出位于 ./public 目录中）。
#          PUBLISH_DIR: ./public
#          # 提交更改时使用的提交消息，从上游分支获取
#          commit_message: ${{ github.event.head_commit.message }}
#          # 自定义域名,CNAME记录.如果没有,可以删除这个参数,使用默认的github pages域名也访问 wangweihong.github.io
#         # cname: ${{ secrets.DOMAIN }}
